export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const SET_SOUND_SELECTED = 'SET_SOUND_SELECTED';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const GET_SOUNDS = 'GET_SOUNDS';
export const GET_SUPERGENS = 'GET_SUPERGENS';